### ISSUE TITLE
apple Chip翻译出错

### ISSUE THREAD

**Issue by Callmebosswang** [akl7777777/bob-plugin-akl-youdao-free-translate#1]
环境：macOS M1 Max python3

翻译出错：
[2023-02-18 14:19:07,315] ERROR in app: Exception on /youdaoTranslate [POST]
Traceback (most recent call last):
  File "flask/app.py", line 2528, in wsgi_app
  File "flask/app.py", line 1825, in full_dispatch_request
  File "flask/app.py", line 1823, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "youdao.py", line 83, in youdaoTranslate
KeyError: 'translateResult'
127.0.0.1 - - [18/Feb/2023 14:19:07] "POST /youdaoTranslate HTTP/1.1" 500 -

**Comment by Callmebosswang** [comment]
@akl7777777 辛苦帮忙排查一下

**Comment by akl7777777** [comment]
看起来是翻译的返回值解析出错,方便提供具体的需要翻译内容,我本地调试一下吗

**Comment by akl7777777** [comment]
@Callmebosswang 已修复,增加了key的判断;请下载新的server文件https://github.com/akl7777777/bob-plugin-akl-youdao-free-translate/releases/download/bob-plugin-akl-youdao-free-translate_v0.0.5/youdaoTranslateServer_macos_x86_64

为了避免后续问题,尽量还是抽空把你翻译的文本信息发给我,我本地调试一下
